/**
 * Customer Server Actions
 *
 * Server actions for the Customer module.
 * Can be called directly from Server Components or via useFormState.
 */

'use server';

import { revalidatePath } from 'next/cache';
import { customerService } from '../services/customer.service';
import {
  customerFormSchema,
  updateCustomerSchema,
} from '../lib/schemas';
import type {
  CustomerListParams,
  Customer,
  CustomerListItem,
  CustomerTableRow,
  CustomerStatus,
  CustomerAddresses,
  CustomerDropdownItem,
} from '../types';
import { createClient } from '@/shared/lib/supabase/server';
import { getAppUserByAuthId } from '@/shared/lib/auth';

// ============================================
// TYPES
// ============================================

export interface ActionResult<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  errors?: Record<string, string[]>;
}

// ============================================
// LIST ACTIONS
// ============================================

/**
 * Get paginated list of customers
 */
export async function getCustomers(
  params: CustomerListParams = {}
): Promise<ActionResult<{
  data: CustomerListItem[];
  meta: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
    hasNextPage: boolean;
    hasPreviousPage: boolean;
  };
}>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  const result = await customerService.list(params);
  return result;
}

/**
 * Get paginated list of customers formatted for table display
 */
export async function getCustomersForTable(
  params: CustomerListParams = {}
): Promise<ActionResult<{
  data: CustomerTableRow[];
  meta: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
    hasNextPage: boolean;
    hasPreviousPage: boolean;
  };
}>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  const result = await customerService.listForTable(params);
  return result;
}

/**
 * Get a single customer by ID
 */
export async function getCustomer(id: string): Promise<ActionResult<Customer>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  return customerService.getById(id);
}

/**
 * Get a single customer by code
 */
export async function getCustomerByCode(code: string): Promise<ActionResult<Customer>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  return customerService.getByCode(code);
}

// ============================================
// CREATE/UPDATE ACTIONS
// ============================================

/**
 * Create a new customer from form data
 */
export async function createCustomer(formData: FormData): Promise<ActionResult<Customer>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  // Get app user ID (public.users.id) from auth user ID
  const appUser = await getAppUserByAuthId(user.id);
  if (!appUser) {
    return { success: false, error: 'User profile not found' };
  }

  // Parse form data (customerCode is auto-generated by service)
  const rawData = {
    customerCode: '', // Auto-generated
    name: formData.get('name') as string,
    legalName: formData.get('legalName') as string || '',
    channel: formData.get('channel') as string || 'dealer',

    // Billing Address
    address1: formData.get('address1') as string || '',
    address2: formData.get('address2') as string || '',
    city: formData.get('city') as string || '',
    state: formData.get('state') as string || '',
    zip: formData.get('zip') as string || '',
    country: formData.get('country') as string || 'US',

    // Shipping Address
    shippingAddress1: formData.get('shippingAddress1') as string || '',
    shippingAddress2: formData.get('shippingAddress2') as string || '',
    shippingCity: formData.get('shippingCity') as string || '',
    shippingState: formData.get('shippingState') as string || '',
    shippingZip: formData.get('shippingZip') as string || '',
    shippingCountry: formData.get('shippingCountry') as string || 'US',
    useSeparateShipping: formData.get('useSeparateShipping') === 'true',

    // Contact
    phone: formData.get('phone') as string || '',
    email: formData.get('email') as string || '',
    website: formData.get('website') as string || '',

    // Tax
    taxId: formData.get('taxId') as string || '',
    taxExempt: formData.get('taxExempt') === 'true',
    taxExemptNumber: formData.get('taxExemptNumber') as string || '',

    // Credit
    creditStatus: formData.get('creditStatus') as string || 'pending',
    creditLimit: formData.get('creditLimit') as string || '0',
    openBalance: formData.get('openBalance') as string || '0',
    creditTerms: formData.get('creditTerms') as string || 'Net 30',

    // Settings
    preferredLocationId: formData.get('preferredLocationId') as string || '',
    defaultPaymentMethod: formData.get('defaultPaymentMethod') as string || '',
    status: formData.get('status') as string || 'active',
    internalNotes: formData.get('internalNotes') as string || '',
  };

  // Validate form data
  const formValidation = customerFormSchema.safeParse(rawData);
  if (!formValidation.success) {
    return {
      success: false,
      error: 'Validation failed',
      errors: formValidation.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  const result = await customerService.createFromForm(formValidation.data, appUser.id);

  if (result.success) {
    revalidatePath('/customers');
    revalidatePath('/api/customers');
  }

  return result;
}

/**
 * Create customer from JSON data
 */
export async function createCustomerFromData(
  data: unknown
): Promise<ActionResult<Customer>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  // Get app user ID (public.users.id) from auth user ID
  const appUser = await getAppUserByAuthId(user.id);
  if (!appUser) {
    return { success: false, error: 'User profile not found' };
  }

  // Validate first
  const formValidation = customerFormSchema.safeParse(data);
  if (!formValidation.success) {
    return {
      success: false,
      error: 'Validation failed',
      errors: formValidation.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  const result = await customerService.createFromForm(formValidation.data, appUser.id);

  if (result.success) {
    revalidatePath('/customers');
    revalidatePath('/api/customers');
  }

  return result;
}

/**
 * Update an existing customer from form data
 */
export async function updateCustomer(
  id: string,
  formData: FormData
): Promise<ActionResult<Customer>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  // Get app user ID (public.users.id) from auth user ID
  const appUser = await getAppUserByAuthId(user.id);
  if (!appUser) {
    return { success: false, error: 'User profile not found' };
  }

  // Parse form data - only include provided fields
  const rawData: Record<string, unknown> = {};

  const stringFields = [
    'customerCode', 'name', 'legalName', 'channel',
    'address1', 'address2', 'city', 'state', 'zip', 'country',
    'shippingAddress1', 'shippingAddress2', 'shippingCity', 'shippingState', 'shippingZip', 'shippingCountry',
    'phone', 'email', 'website',
    'taxId', 'taxExemptNumber',
    'creditStatus', 'creditTerms',
    'preferredLocationId', 'defaultPaymentMethod', 'status', 'internalNotes'
  ];

  for (const field of stringFields) {
    const value = formData.get(field);
    if (value !== null) {
      rawData[field] = value === '' ? null : value;
    }
  }

  // Handle boolean fields
  if (formData.has('useSeparateShipping')) {
    rawData.useSeparateShipping = formData.get('useSeparateShipping') === 'true';
  }
  if (formData.has('taxExempt')) {
    rawData.taxExempt = formData.get('taxExempt') === 'true';
  }

  // Handle credit limit (convert to cents)
  if (formData.has('creditLimit')) {
    const creditLimitStr = formData.get('creditLimit') as string;
    rawData.creditLimit = Math.round(parseFloat(creditLimitStr || '0') * 100);
  }

  // Handle open balance (convert to cents)
  if (formData.has('openBalance')) {
    const openBalanceStr = formData.get('openBalance') as string;
    rawData.openBalance = Math.round(parseFloat(openBalanceStr || '0') * 100);
  }

  // Uppercase customer code if provided
  if (rawData.customerCode) {
    rawData.customerCode = (rawData.customerCode as string).toUpperCase();
  }

  // Validate
  const validation = updateCustomerSchema.safeParse(rawData);
  if (!validation.success) {
    return {
      success: false,
      error: 'Validation failed',
      errors: validation.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  const result = await customerService.update(id, validation.data, appUser.id);

  if (result.success) {
    revalidatePath('/customers');
    revalidatePath(`/customers/${id}`);
    revalidatePath('/api/customers');
  }

  return result;
}

/**
 * Update customer from JSON data
 */
export async function updateCustomerFromData(
  id: string,
  data: unknown
): Promise<ActionResult<Customer>> {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return { success: false, error: 'Authentication required' };
    }

    // Get app user ID (public.users.id) from auth user ID
    const appUser = await getAppUserByAuthId(user.id);
    if (!appUser) {
      return { success: false, error: 'User profile not found' };
    }

    // If data is form values, convert to DTO format
    const dataObj = data as Record<string, unknown>;
    const convertedData = typeof data === 'object' && data !== null
      ? {
          ...data,
          creditLimit: 'creditLimit' in dataObj && typeof dataObj.creditLimit === 'string'
            ? Math.round(parseFloat(dataObj.creditLimit as string || '0') * 100)
            : dataObj.creditLimit,
          openBalance: 'openBalance' in dataObj && typeof dataObj.openBalance === 'string'
            ? Math.round(parseFloat(dataObj.openBalance as string || '0') * 100)
            : dataObj.openBalance,
        }
      : data;

    // Validate
    const validation = updateCustomerSchema.safeParse(convertedData);
    if (!validation.success) {
      return {
        success: false,
        error: 'Validation failed',
        errors: validation.error.flatten().fieldErrors as Record<string, string[]>,
      };
    }

    const result = await customerService.update(id, validation.data, appUser.id);

    if (result.success) {
      revalidatePath('/customers');
      revalidatePath(`/customers/${id}`);
      revalidatePath('/api/customers');
    }

    return result;
  } catch (error) {
    console.error('updateCustomerFromData unexpected error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to update customer',
    };
  }
}

/**
 * Soft delete a customer
 */
export async function deleteCustomer(id: string): Promise<ActionResult<Customer>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  // Get app user ID (public.users.id) from auth user ID
  const appUser = await getAppUserByAuthId(user.id);
  if (!appUser) {
    return { success: false, error: 'User profile not found' };
  }

  const result = await customerService.delete(id, appUser.id);

  if (result.success) {
    revalidatePath('/customers');
    revalidatePath('/api/customers');
  }

  return result;
}

/**
 * Restore a soft-deleted customer
 */
export async function restoreCustomer(id: string): Promise<ActionResult<Customer>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  // Get app user ID (public.users.id) from auth user ID
  const appUser = await getAppUserByAuthId(user.id);
  if (!appUser) {
    return { success: false, error: 'User profile not found' };
  }

  const result = await customerService.restore(id, appUser.id);

  if (result.success) {
    revalidatePath('/customers');
    revalidatePath('/api/customers');
  }

  return result;
}

// ============================================
// VALIDATION ACTIONS
// ============================================

/**
 * Validate customer code uniqueness
 */
export async function validateCustomerCode(
  code: string,
  excludeId?: string
): Promise<ActionResult<boolean>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  return customerService.validateCode(code.toUpperCase(), excludeId);
}

/**
 * Validate customer email uniqueness
 */
export async function validateCustomerEmail(
  email: string,
  excludeId?: string
): Promise<ActionResult<boolean>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  return customerService.validateEmail(email, excludeId);
}

// ============================================
// UTILITY ACTIONS
// ============================================

/**
 * Get next auto-generated customer code
 */
export async function getNextCustomerCode(): Promise<ActionResult<string>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  return customerService.getNextCode();
}

/**
 * Get customer counts by status
 */
export async function getCustomerStatusCounts(): Promise<ActionResult<Record<CustomerStatus, number>>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  return customerService.getStatusCounts();
}

/**
 * Get customer addresses for auto-fill (used by Sales Orders)
 */
export async function getCustomerAddresses(
  customerId: string
): Promise<ActionResult<CustomerAddresses>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  return customerService.getAddresses(customerId);
}

/**
 * Get customers for dropdown/select
 */
export async function getCustomersForDropdown(): Promise<ActionResult<CustomerDropdownItem[]>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  return customerService.getForDropdown();
}

// ============================================
// QBO SYNC ACTIONS
// ============================================

/**
 * Get QBO sync status for a customer
 */
export async function getCustomerQboSyncStatus(
  customerId: string
): Promise<ActionResult<{
  synced: boolean;
  qboCustomerId?: string;
  lastSyncedAt?: Date;
  syncStatus?: string;
  lastError?: string;
}>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  return customerService.getQboSyncStatus(customerId);
}

/**
 * Manually trigger QBO sync for a customer
 */
export async function resyncCustomerToQbo(
  customerId: string
): Promise<ActionResult<{ qboCustomerId?: string }>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: 'Authentication required' };
  }

  // Get app user ID (public.users.id) from auth user ID
  const appUser = await getAppUserByAuthId(user.id);
  if (!appUser) {
    return { success: false, error: 'User profile not found' };
  }

  const result = await customerService.resyncCustomerToQbo(customerId, appUser.id);

  if (result.success) {
    revalidatePath(`/customers/${customerId}`);
  }

  return result;
}
