/**
 * Database Types
 *
 * Defines database-related types for use throughout the application.
 * These types were previously generated by Drizzle ORM but are now manually defined.
 */

// ============================================
// ENUM TYPES
// ============================================

export type UserStatus = 'active' | 'inactive' | 'suspended' | 'pending';
export type AuditAction = 'create' | 'update' | 'delete' | 'restore' | 'login' | 'logout' | 'password_change' | 'role_assign' | 'export' | 'import';
export type CustomerChannel = 'direct' | 'wholesale' | 'retail' | 'online';
export type CustomerStatus = 'active' | 'inactive' | 'suspended' | 'pending';
export type CreditStatus = 'good' | 'warning' | 'hold' | 'cod_only';
export type ContactType = 'primary' | 'billing' | 'shipping' | 'purchasing' | 'ap' | 'other';
export type CustomerDocumentType = 'tax_exempt' | 'resale_cert' | 'credit_app' | 'contract' | 'other';
export type DocumentStatus = 'pending' | 'approved' | 'rejected' | 'expired';
export type ProductStatus = 'active' | 'inactive' | 'discontinued';
export type LocationType = 'warehouse' | 'drop_ship' | 'virtual';
export type PriceStatus = 'active' | 'inactive' | 'pending';

// ============================================
// COMMON QUERY TYPES
// ============================================

/**
 * Pagination parameters
 */
export interface PaginationParams {
  page: number;
  pageSize: number;
}

/**
 * Sort parameters
 */
export interface SortParams<T> {
  field: keyof T;
  direction: 'asc' | 'desc';
}

/**
 * Paginated response
 */
export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    page: number;
    pageSize: number;
    totalCount: number;
    totalPages: number;
    hasNextPage: boolean;
    hasPreviousPage: boolean;
  };
}

// ============================================
// FILTER TYPES
// ============================================

/**
 * Common filter operators
 */
export interface FilterOperators<T> {
  equals?: T;
  not?: T;
  in?: T[];
  notIn?: T[];
  contains?: string;
  startsWith?: string;
  endsWith?: string;
  gt?: T;
  gte?: T;
  lt?: T;
  lte?: T;
}

/**
 * Date range filter
 */
export interface DateRangeFilter {
  from?: Date;
  to?: Date;
}
